In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests

In [2]:
# Import the API key.
from config import gkey

In [3]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.dropna(inplace = True) 
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Finschhafen,PG,2022-01-20 22:43:46,-6.6024,147.8681,81.77,77,99,1.90
1,1,Albany,US,2022-01-20 22:40:46,42.6001,-73.9662,20.48,57,23,15.99
2,2,Hobart,AU,2022-01-20 22:43:47,-42.8794,147.3294,71.02,61,0,1.01
3,3,Cape Town,ZA,2022-01-20 22:42:50,-33.9258,18.4232,66.27,75,0,5.01
4,4,Yamasaki,JP,2022-01-20 22:43:47,35.0000,134.5500,36.48,87,22,3.27

In [4]:
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [5]:
# Configure gmaps to use your Google API key.
gmaps.configure(gkey)

In [6]:
# Get the maximum temperature.
#max_temp = city_data_df["Max Temp"]
#temps = []
#for temp in max_temp:
    #temps.append(max(temp, 0))

In [7]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]

In [8]:
# Plot Heatmap
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.2)

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp], 
                                 dissipating=False, max_intensity=300,
                                 point_radius=4)


# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [10]:
# Heatmap of percent Cloudiness
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [11]:
# Heatmap of percent Wind Speed
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [12]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 70
What is the maximum temperature you would like for your trip? 90

In [13]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Finschhafen,PG,2022-01-20 22:43:46,-6.6024,147.8681,81.77,77,99,1.90
2,2,Hobart,AU,2022-01-20 22:43:47,-42.8794,147.3294,71.02,61,0,1.01
6,6,Hilo,US,2022-01-20 22:43:48,19.7297,-155.0900,78.80,69,75,10.36
7,7,Rikitea,PF,2022-01-20 22:43:48,-23.1203,-134.9692,78.57,73,100,8.50
8,8,Kampot,KH,2022-01-20 22:43:49,10.6167,104.1833,71.65,83,18,2.33
9,9,Lorengau,PG,2022-01-20 22:43:49,-2.0226,147.2712,81.68,78,100,6.80
11,11,Codrington,AU,2022-01-20 22:43:51,-38.2667,141.9667,80.83,32,0,8.99
12,12,Noumea,NC,2022-01-20 22:43:51,-22.2763,166.4572,80.01,99,90,12.57
15,15,Amapa,BR,2022-01-20 22:43:52,1.0000,-52.0000,72.39,99,80,2.89
18,18,Itapirapua,BR,2022-01-20 22:43:52,-15.8233,-50.6133,74.79,82,8,3.67

In [14]:
preferred_cities_df.count()

City_ID       217
City          217
Country       217
Date          217
Lat           217
Lng           217
Max Temp      217
Humidity      217
Cloudiness    217
Wind Speed    217
dtype: int64

In [15]:
preferred_cities_df.dropna()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Finschhafen,PG,2022-01-20 22:43:46,-6.6024,147.8681,81.77,77,99,1.90
2,2,Hobart,AU,2022-01-20 22:43:47,-42.8794,147.3294,71.02,61,0,1.01
6,6,Hilo,US,2022-01-20 22:43:48,19.7297,-155.0900,78.80,69,75,10.36
7,7,Rikitea,PF,2022-01-20 22:43:48,-23.1203,-134.9692,78.57,73,100,8.50
8,8,Kampot,KH,2022-01-20 22:43:49,10.6167,104.1833,71.65,83,18,2.33
...,...,...,...,...,...,...,...,...,...,...
577,577,Grand-Santi,GF,2022-01-20 22:58:37,4.2500,-54.3833,72.79,98,100,2.62
579,579,Makakilo City,US,2022-01-20 22:58:37,21.3469,-158.0858,78.62,67,21,5.53
584,584,Maxixe,MZ,2022-01-20 22:58:39,-23.8597,35.3472,74.44,76,91,9.78
586,586,Charters Towers,AU,2022-01-20 22:58:40,-20.1000,146.2667,81.90,54,74,16.44
587,587,Eldorado,BR,2022-01-20 22:58:40,-23.7869,-54.2836,77.68,68,79,10.33

In [16]:
preferred_cities_df.count()

City_ID       217
City          217
Country       217
Date          217
Lat           217
Lng           217
Max Temp      217
Humidity      217
Cloudiness    217
Wind Speed    217
dtype: int64

In [17]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

           City Country  Max Temp      Lat       Lng Hotel Name
0   Finschhafen      PG     81.77  -6.6024  147.8681
2        Hobart      AU     71.02 -42.8794  147.3294
6          Hilo      US     78.80  19.7297 -155.0900
7       Rikitea      PF     78.57 -23.1203 -134.9692
8        Kampot      KH     71.65  10.6167  104.1833
9      Lorengau      PG     81.68  -2.0226  147.2712
11   Codrington      AU     80.83 -38.2667  141.9667
12       Noumea      NC     80.01 -22.2763  166.4572
15        Amapa      BR     72.39   1.0000  -52.0000
18   Itapirapua      BR     74.79 -15.8233  -50.6133

In [33]:
# Set the parameters to search for a hotel in Paris.
params = {
    "radius": 5000,
    "types": "lodging",
    "key": gkey,
    "location": "48.8566, 2.3522"}
# Use base URL to search for hotels in Paris.
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
# Make request and get the JSON data from the search.
hotels = requests.get(base_url, params=params).json()

hotels

{'html_attributions': [],
 'next_page_token': 'Aap_uEBsTv407nkdXBSfa4azrZ0y2A5i0nqqPMFyOAJg0jaVQ0cjFrAkDySyuzFeLCaLSKqSGQoY65snX7M4BiWizqP04vsBFh5npy_TPH20t2wCYOQzfgPTbdxOln_wGfrQPFtqoxSe-VkZ-oGQIXyozJ32GdGuYjMmJVLObaMZ2EwacM8ue9j-rTpvQ5X37F7mC0UV8nWFqCRkyjBbz30SQXsGORroByGVO2DgIzEiFySK6KN_cBSsrk5zpAAzWQ4Bk3qEppb2iIDsQrDPeWl0ZnQU4da3_vvCdQrWrsSB-4K4EaU-v_6biYPR61y6uqVUC8f0dI_fimyUF0eQMZGOAT-e-6mwedwM-U1JATo9NH64KQBO_2qy9NRTDdbAcpRHsNv7ZO1TsjxBA_OkF9imV_NTiOoE9hJoMCPh1WCT0F1YEBs9EbKFrrNx',
 'results': [{'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8581126, 'lng': 2.3529277},
    'viewport': {'northeast': {'lat': 48.8594360302915,
      'lng': 2.354355480291502},
     'southwest': {'lat': 48.8567380697085, 'lng': 2.351657519708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Duo',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3840,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/107554201425443337224">Hôtel Duo</a>'],
     'photo_reference': 'Aap_uEBRsjA3418Sg2p_aE68RfNpYBYlPiOAPZB-3FikO9_JhIx_hN4CwEavgm2Am9AOHEt8D8-f-1chlCYn_0DQbHJg7NrslWPgSMrQE2UVRoiNR9F9_rDbXb1dfuiYbl45QbLoP3BaHKtrru68pA53cL9nmB8vt_anHz-gD8xP9zNJjOwq',
     'width': 5760}],
   'place_id': 'ChIJWU9CqB1u5kcR5P1F2SMoJmc',
   'plus_code': {'compound_code': 'V953+65 Paris, France',
    'global_code': '8FW4V953+65'},
   'rating': 4.2,
   'reference': 'ChIJWU9CqB1u5kcR5P1F2SMoJmc',
   'scope': 'GOOGLE',
   'types': ['night_club',
    'spa',
    'lodging',
    'bar',
    'gym',
    'health',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 317,
   'vicinity': '11 Rue du Temple, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8582861, 'lng': 2.3464944},
    'viewport': {'northeast': {'lat': 48.85954748029151,
      'lng': 2.347782830291502},
     'southwest': {'lat': 48.85684951970851, 'lng': 2.345084869708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Britannique - Paris Centre',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1426,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/108984000175492464929">Hôtel Britannique - Paris Centre</a>'],
     'photo_reference': 'Aap_uECrS-xBMV7nNWA6l87wiJ19EsH6-t4yYw6Oa3pYPqFBaAGy_uHHDR1z2CVTI9FMPyZkfPVQwyljQMw2t4jewX7EeYLoBGMtWCJ1QFCb-oCObllAtKhDUtDRoG3FXkQlXkSrUQRAgLpnHZOOSys44JDx35a7ZsT1-pqy3Osdr5_ypvvX',
     'width': 1476}],
   'place_id': 'ChIJ-4Siox9u5kcRm9vM6DcMXyU',
   'plus_code': {'compound_code': 'V85W+8H Paris, France',
    'global_code': '8FW4V85W+8H'},
   'rating': 4.6,
   'reference': 'ChIJ-4Siox9u5kcRm9vM6DcMXyU',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 679,
   'vicinity': '20 Avenue Victoria, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8606655, 'lng': 2.3469293},
    'viewport': {'northeast': {'lat': 48.8617746302915,
      'lng': 2.347927730291502},
     'southwest': {'lat': 48.8590766697085, 'lng': 2.345229769708499}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Citadines Les Halles Paris',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 853,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/102565262508115704337">Citadines Les Halles Paris (Apart hotel Paris)</a>'],
     'photo_reference': 'Aap_uEAMEfFyPiZ4JXxdyC80-m2ca01Et7rPYHMY5kYqBzii46koWpZ7e3KBaJ2gEaTKoxl8Ti9GLRdXRZgxkNd1Et6lXZriBMMJWTxzXA-L48Yhug-KFLJJH_HZDUHOaxFy84sSJM-xmk3yRkvOcsWyewf8A6Utb4sJ8CV9EI9E3KJT25-l',
     'width': 1280}],
   'place_id': 'ChIJQ_QDrxhu5kcRJzNxLLEOSfU',
   'plus_code': {'compound_code': 'V86W+7Q Paris, France',
    'global_code': '8FW4V86W+7Q'},
   'rating': 4.1,
   'reference': 'ChIJQ_QDrxhu5kcRJzNxLLEOSfU',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 890,
   'vicinity': '4 Rue des Innocents, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8607658, 'lng': 2.3465318},
    'viewport': {'northeast': {'lat': 48.8620584302915,
      'lng': 2.347692880291501},
     'southwest': {'lat': 48.85936046970851, 'lng': 2.344994919708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Novotel Paris Les Halles',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2000,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/111815616573299411056">Novotel Paris Les Halles</a>'],
     'photo_reference': 'Aap_uEBXJsWQSD8Lb-rSGM9E18xyke16nGhds27IjpPqQ8sDuUxsmmqFdJR9m4cagYPXbWKT3lGzH5qKuxti61fmiq7pE2gTRnWtPQH8kpO2CQ1RjaQWjqMM-pQt5iTQcpJlFmtMbeSzCC72wVr3lE8iMNYl58e2O-Ypo6y6pOxh2I5rjN7A',
     'width': 3000}],
   'place_id': 'ChIJGW2pNx9u5kcRI3oyL8NG5BQ',
   'plus_code': {'compound_code': 'V86W+8J Paris, France',
    'global_code': '8FW4V86W+8J'},
   'rating': 4.4,
   'reference': 'ChIJGW2pNx9u5kcRI3oyL8NG5BQ',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 2346,
   'vicinity': '8 Place Marguerite de Navarre, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.860352, 'lng': 2.3440948},
    'viewport': {'northeast': {'lat': 48.86165553029149,
      'lng': 2.345549080291502},
     'southwest': {'lat': 48.8589575697085, 'lng': 2.342851119708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Ducs de Bourgogne',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1390,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/101411638353598558320">Hôtel Ducs de Bourgogne</a>'],
     'photo_reference': 'Aap_uEBo2H1h1IB8azrnss-kdEATm7C7wlLaCK0rwGz4UmAw2y2qL7u_VO3FMP6fUpG-k_ivwchezzbTbSwKO_eX84Ud2f5EaBWiEDmivDg851rEyisxla2Kf1xX_-bEnZ7-hczUfEQXIlQAVmQmh_L66ZgV6xAUrKZsM-hPtxE2rk1iY8pe',
     'width': 2048}],
   'place_id': 'ChIJifTG5yFu5kcRdnisbwxnAx4',
   'plus_code': {'compound_code': 'V86V+4J Paris, France',
    'global_code': '8FW4V86V+4J'},
   'rating': 4.5,
   'reference': 'ChIJifTG5yFu5kcRdnisbwxnAx4',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 284,
   'vicinity': '19 Rue du Pont Neuf, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8555091, 'lng': 2.3408736},
    'viewport': {'northeast': {'lat': 48.8569076302915,
      'lng': 2.342319280291502},
     'southwest': {'lat': 48.8542096697085, 'lng': 2.339621319708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Citadines Saint-Germain-des-Prés Paris (Apart hotel Paris)',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 4480,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/113188832595116816387">Citadines Saint-Germain-des-Prés Paris</a>'],
     'photo_reference': 'Aap_uEDRHI3hZMlWeMMuN8MleWXqRpUJFXqb4HA-H-DuwaE5_kvN1jDVyIal_l5OiOaawdmAo_ifz4AyVhV0D_eTvLcMH6ELX2-qxNDR7PyC3jiSCC8TQa8qKim-B5HcyBho8bKSOHrQj7PWnFASRL2PxQu9n6SBPobGgnT-ohmjWwAwqfUt',
     'width': 6720}],
   'place_id': 'ChIJo5pYcN9x5kcRERXdocMgqmE',
   'plus_code': {'compound_code': 'V84R+68 Paris, France',
    'global_code': '8FW4V84R+68'},
   'rating': 4.3,
   'reference': 'ChIJo5pYcN9x5kcRERXdocMgqmE',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 721,
   'vicinity': '53 ter Quai des Grands Augustins, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8663519, 'lng': 2.3606461},
    'viewport': {'northeast': {'lat': 48.86775308029149,
      'lng': 2.361905130291502},
     'southwest': {'lat': 48.8650551197085, 'lng': 2.359207169708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Paris France Hôtel',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2673,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/102332962500946068613">Paris France Hôtel</a>'],
     'photo_reference': 'Aap_uED-qDLOoD5EXUfy_pq_fZ49QzjQlHbKaVmmTCROGQVJmOrcYmVME9u-tnGiFNiVCtpM1OVEuHoGvfg_ABevgVCoXyrMpQFQbiJosKogr7aHE4AkZ5QpDMD6qgP0EJ3qmd9LXBfv9-LpwaLs316BIsvLJdYwTECA73rpea6S1s8SkTT-',
     'width': 3463}],
   'place_id': 'ChIJhXWLZg9u5kcRDVyqoZYgcmg',
   'plus_code': {'compound_code': 'V986+G7 Paris, France',
    'global_code': '8FW4V986+G7'},
   'rating': 4.3,
   'reference': 'ChIJhXWLZg9u5kcRDVyqoZYgcmg',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 402,
   'vicinity': '72 Rue de Turbigo, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.86386539999999, 'lng': 2.3325488},
    'viewport': {'northeast': {'lat': 48.8650759802915,
      'lng': 2.333775730291502},
     'southwest': {'lat': 48.8623780197085, 'lng': 2.331077769708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hotel Regina Louvre',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3700,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/109908333790946649027">Hôtel Regina Louvre</a>'],
     'photo_reference': 'Aap_uEB0eoCNZ47Bx_IE2dU7Flgy3jS-yy92LgzNYAoJxRyqyaWRl82YTzj0RQ8FyMh5WyQoPUHe-p3DmEywW0P3rPzwrvc-P1_WotlwGnan--7XHyhuq7Gjy5OuJhXvs8FHQmUed5nE4ZSr8fCGm3XybPJiINRvKil3ZAiKcXcIULWTn7xs',
     'width': 5550}],
   'place_id': 'ChIJP_-HCS9u5kcRsj9b1x7Pl8w',
   'plus_code': {'compound_code': 'V87M+G2 Paris, France',
    'global_code': '8FW4V87M+G2'},
   'rating': 4.5,
   'reference': 'ChIJP_-HCS9u5kcRsj9b1x7Pl8w',
   'scope': 'GOOGLE',
   'types': ['lodging',
    'bar',
    'restaurant',
    'food',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 509,
   'vicinity': '2 Place des Pyramides, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.84795229999999, 'lng': 2.370869},
    'viewport': {'northeast': {'lat': 48.8492035302915,
      'lng': 2.372290080291501},
     'southwest': {'lat': 48.8465055697085, 'lng': 2.369592119708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'ibis Paris Gare de Lyon Ledru Rollin 12ème',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2048,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/101181280085797863615">Kevin Nguyen</a>'],
     'photo_reference': 'Aap_uEBXPjfOiZzAHWkR8FNxH3OhihDo_n4UdzOCv3sPjJnx4IVoapTNyc51tH9IoEiKGch7jwBXeSsC_6oB48EGF5FePJQYwzt05-v_7xaMq9Sr40Jx5rI5FSTwZmkMFpm-WY5LVlELJyx_EpgFk721KgkPWsLFXRMXHrKg--aDMiS8xYk-',
     'width': 1536}],
   'place_id': 'ChIJ9RNxcQNy5kcRnZJ4vsuXcow',
   'plus_code': {'compound_code': 'R9XC+58 Paris, France',
    'global_code': '8FW4R9XC+58'},
   'rating': 4.1,
   'reference': 'ChIJ9RNxcQNy5kcRnZJ4vsuXcow',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 857,
   'vicinity': '41/43 Avenue Ledru Rollin, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8710647, 'lng': 2.34991},
    'viewport': {'northeast': {'lat': 48.87241888029151,
      'lng': 2.351188530291502},
     'southwest': {'lat': 48.86972091970851, 'lng': 2.348490569708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel des Comédies Paris',
   'photos': [{'height': 4000,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/114696623290303183213">Noble</a>'],
     'photo_reference': 'Aap_uEAB3OTQDOAtb_la4-y_2XoAOgfQKGr3EKSPxknmVzwoUMMGDFDd04zIzMUJB92lunHV-XWy5xMeoH8RB8p6oMBnndGnrJitn8dO277OUOykQVEI6cJASEbnceuskQROBVy_kujJBW4V_hO3-khXZNNHMJ9gGchOmkNfY6fvzuA0_0y-',
     'width': 3000}],
   'place_id': 'ChIJn6ginxZu5kcRmAEK0OHm0cI',
   'plus_code': {'compound_code': 'V8CX+CX Paris, France',
    'global_code': '8FW4V8CX+CX'},
   'rating': 4.3,
   'reference': 'ChIJn6ginxZu5kcRmAEK0OHm0cI',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 200,
   'vicinity': "8 Rue d'Hauteville, Paris"},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.84754640000001, 'lng': 2.3718722},
    'viewport': {'northeast': {'lat': 48.8488820802915,
      'lng': 2.373123430291502},
     'southwest': {'lat': 48.8461841197085, 'lng': 2.370425469708499}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel De France Gare de Lyon Bastille',
   'photos': [{'height': 787,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/117462031751048846575">Hôtel De France Gare de Lyon Bastille</a>'],
     'photo_reference': 'Aap_uECgSPjThvGEsanMVJMo4dQufcy0P0qmJYLuiF9QChWCAPxzxb86pxLbpnnvksTziHqd-uAQGJM7knHlB2rSQGxRiHyiQ2M_blMPjvvVesun_uPe2RpnNzT0QrP7djSq2A_VueaZKLavI8xj6uaDUx2RQyVmTvze2zYM7kQ198-SDsO3',
     'width': 1181}],
   'place_id': 'ChIJz6DBYgNy5kcRhOu1LhDIECM',
   'plus_code': {'compound_code': 'R9XC+2P Paris, France',
    'global_code': '8FW4R9XC+2P'},
   'rating': 3.3,
   'reference': 'ChIJz6DBYgNy5kcRhOu1LhDIECM',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 383,
   'vicinity': '12 Rue de Lyon, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8717386, 'lng': 2.3447052},
    'viewport': {'northeast': {'lat': 48.8731374802915,
      'lng': 2.346059980291502},
     'southwest': {'lat': 48.8704395197085, 'lng': 2.343362019708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Prélude Opéra Paris',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2448,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/106224131803115407650">Marcin Marczak</a>'],
     'photo_reference': 'Aap_uEAMX5p0gROTHkPX2VBzEO3OmfYRPSATQzjtnzk1bTJn4o5cU5pOd9_6_ICrvPrt7xrgkm98YuJTY6F7aXhXrJniCKMkjcwZziWMI07K5KSL8bJAwlKP0cAYIU9LdpJFqPu8LWBsoT5ZclTLl0o56fWArIQQptKVIP59wqkTCCw8u_nB',
     'width': 3264}],
   'place_id': 'ChIJ8e3Qcj5u5kcR2MIGwNxustk',
   'plus_code': {'compound_code': 'V8CV+MV Paris, France',
    'global_code': '8FW4V8CV+MV'},
   'rating': 4.2,
   'reference': 'ChIJ8e3Qcj5u5kcR2MIGwNxustk',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 408,
   'vicinity': '8 Cité Bergère, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8423434, 'lng': 2.3632087},
    'viewport': {'northeast': {'lat': 48.8436624802915,
      'lng': 2.364700930291502},
     'southwest': {'lat': 48.8409645197085, 'lng': 2.362002969708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Libertel Austerlitz Jardin des Plantes',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 4480,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/114802271282641766772">Hôtel Libertel Austerlitz Jardin des Plantes</a>'],
     'photo_reference': 'Aap_uEDEPqb1Pfqz7MLJaNstPwKI8_-uwpdXavbOOdI4qvwlxFlRm0Y08HZfN6dXhOZwCXKapGN6_rFAOAMNHE6cK990uWAcainnSbZVTQhNEjJo1AggTlg_cJPHge6wmBl-F1ycSkZsdlj_6SbHtAj9HcqLNcNecb1rFR49tRKOgQCKzgAb',
     'width': 6720}],
   'place_id': 'ChIJe-udXPZx5kcRKURHNFv5BSw',
   'plus_code': {'compound_code': 'R9R7+W7 Paris, France',
    'global_code': '8FW4R9R7+W7'},
   'rating': 3.9,
   'reference': 'ChIJe-udXPZx5kcRKURHNFv5BSw',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 462,
   'vicinity': "12 Boulevard de l'Hôpital, Paris"},
  {'business_status': 'CLOSED_TEMPORARILY',
   'geometry': {'location': {'lat': 48.8642974, 'lng': 2.3308142},
    'viewport': {'northeast': {'lat': 48.8655789302915,
      'lng': 2.332153980291502},
     'southwest': {'lat': 48.8628809697085, 'lng': 2.329456019708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Saint James Albany Paris Hôtel Spa',
   'permanently_closed': True,
   'photos': [{'height': 400,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/108570400659068256718">Saint James Albany Paris Hôtel Spa</a>'],
     'photo_reference': 'Aap_uEDmAdHGUROPY0DCOjh78Oc7JbosxURpGC4YYoIXuOnRc-QOd6NQQ96_TJzTH4-y-yNNh_IVqLE-ymHEUeet48Cj1G-o7MUg6Q3WBqcgJNOBB-G2PH_Fsz4fNTGVyZn2X9BLdvxIYRLWEEDXMje88aM05Ffgc_c4NPK1fHUgwUe2udWI',
     'width': 600}],
   'place_id': 'ChIJ8znTVS5u5kcREq8TmzOICFs',
   'plus_code': {'compound_code': 'V87J+P8 Paris, France',
    'global_code': '8FW4V87J+P8'},
   'rating': 4,
   'reference': 'ChIJ8znTVS5u5kcREq8TmzOICFs',
   'scope': 'GOOGLE',
   'types': ['lodging',
    'bar',
    'restaurant',
    'food',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 1074,
   'vicinity': '202 Rue de Rivoli, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.87110329999999, 'lng': 2.3389728},
    'viewport': {'northeast': {'lat': 48.8724169302915,
      'lng': 2.340369280291502},
     'southwest': {'lat': 48.8697189697085, 'lng': 2.337671319708499}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Icône',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1066,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/108137830440312077288">Hôtel Icône</a>'],

In [41]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    #hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    
# Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [42]:
hotel_df.head(10)

,City,Country,Max Temp,Lat,Lng,Hotel Name
0,Finschhafen,PG,81.77,-6.6024,147.8681,Cossam Guest House
2,Hobart,AU,71.02,-42.8794,147.3294,Mantra on Collins Hobart
6,Hilo,US,78.80,19.7297,-155.0900,Hilo Hawaiian Hotel
7,Rikitea,PF,78.57,-23.1203,-134.9692,People ThankYou
8,Kampot,KH,71.65,10.6167,104.1833,Two Moons Hotel
9,Lorengau,PG,81.68,-2.0226,147.2712,Lorengau Harbourside Hotel
11,Codrington,AU,80.83,-38.2667,141.9667,Codrington Gardens Bed And Breakfast
12,Noumea,NC,80.01,-22.2763,166.4572,Hôtel Le Lagon
15,Amapa,BR,72.39,1.0000,-52.0000,
18,Itapirapua,BR,74.79,-15.8233,-50.6133,Hotel Nossa Senhora Aparecida

In [43]:
# Add a heatmap of temperature for the vacation spots.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [44]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [45]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [46]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))